# Potential papers to Publish in


## <a href="https://www-sciencedirect-com.ezproxy.aut.ac.nz/journal/remote-sensing-of-environment/about/aims-and-scope" style="color:green">Remote Sensing of Environment</a>

Drawbacks: 

Cost: 

Impact Facor: 11.1

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)




## <a href="https://www.tandfonline.com/journals/trsl20/about-this-journal#aims-and-scope" style="color:green">Remote Sensing Letters</a>

- Sister journal of International Journal of Remote Sensing
- 12 page limit

Drawbacks: 

Cost: free

Impact Facor: 1.4

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)




## <a href="https://link.springer.com/journal/41976/aims-and-scope" style="color:orange">Remote Sensing in Earth Systems Sciences</a>

Drawbacks: low rankings

Cost: free

Impact Facor: (1.6) not from officil website 

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)


## <a href="https://www-sciencedirect-com.ezproxy.aut.ac.nz/journal/remote-sensing-applications-society-and-environment/about/aims-and-scope" style="color:green">Remote Sensing Applications: Society and Environment</a>

Drawbacks: 

Cost: free

Impact Facor: 3.8

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)

## <a href="https://link.springer.com/journal/41064/aims-and-scope" style="color:orange">Journal of Photogrammetry, Remote Sensing and Geoinformation Science</a>

Drawbacks: 

Cost: free

Impact Facor: 2.1

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)



## <a href="https://www-sciencedirect-com.ezproxy.aut.ac.nz/journal/isprs-journal-of-photogrammetry-and-remote-sensing/about/aims-and-scope" style="color:orange">ISPRS Journal of Photogrammetry and Remote Sensing</a>

Drawbacks: 

Cost: free

Impact Facor: 10.6

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)


## <a href="https://zslpublications.onlinelibrary.wiley.com/hub/journal/20563485/aims-scopes" style="color:green">Remote Sensing in Ecology and Conservation</a>

Drawbacks: only 16% acceptance rate

Cost: free

Impact Facor: 3.9

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)


## <a href="https://www.tandfonline.com/journals/tres20/about-this-journal#aims-and-scope" style="color:green">International Journal of Remote Sensing</a>

Sister journal of Remote Sensing Letters

Drawbacks: only 16% acceptance rate

Impact Facor: 3.0

Cost: free

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)

## <a href="https://esajournals.onlinelibrary.wiley.com/hub/journal/15409309/aims-and-scope/read-full-aims-and-scope" style="color:orange">Frontiers in Ecology and the Environment</a>

Drawbacks: Research not relevant enough on a global scale

Impact Facor: 10.0

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)


## <a href="https://www.mdpi.com/journal/plants" style="color:orange">Plants</a>

Drawbacks: Might be difficult to get accepted

Cost: 2700 CHF (5000 NZD)

Impact Facor: 4.0

Found via: [Jane](https://jane.biosemantics.org/index.php)


## <a href="https://journals.plos.org/plosbiology/s/journal-information#loc-scope" style="color:orange">PLOS Biology</a>

Drawbacks: 

Cost: [3400 USD](https://plos.org/fees/)(*authors will only incur fees if their institutions are not members of the journal’s collective action community*)


Impact Facor: 7.8


Found via: [Jane](https://jane.biosemantics.org/index.php)



## <a href="https://www.frontiersin.org/journals/plant-science/about#about-scope" style="color:green">Frontiers in Plant Science</a>

Drawbacks: 

Cost: [3150 CHF](https://www.frontiersin.org/journals/plant-science/for-authors/publishing-fees)

Impact Facor: 4.1

Found via: [Jane](https://jane.biosemantics.org/index.php)






## <a href="https://onlinelibrary.wiley.com/page/journal/14390434/homepage/forauthors.html" style="color:orange">Journal of Phytopathology</a>

Drawbacks: *Journal of Phytopathology publishes original and review articles on all scientific aspects of phytopathology in agricultural and horticultural crops.*

Impact Facor: 2.9

Found via: [Jane](https://jane.biosemantics.org/index.php)


## <a href="https://link.springer.com/journal/41348/aims-and-scope" style="color:orange">Plant Disease</a>

Drawbacks: research must have relevance fpr European plant health

Impact Facor: 2.2

Found via: [Jane](https://jane.biosemantics.org/index.php)

## <a href="https://link.springer.com/journal/10531/aims-and-scope" style="color:red">Biodiversity and Conservation</a>

Drawbacks: *Note that, unless of value as case studies using novel approaches, the journal rarely accepts papers on single species not of major importance or concern, or studies documenting local biodiversity.*

Cost: free

Impact Facor: 3.0

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)


## <a href="" style="color:orange">Title</a>

Drawbacks: 

Cost: 

Impact Facor: 

Found via: [CAUL 2025 Journal Title List](https://airtable.com/appVv3skr5sxCDhKr/shryMoaBW4oQjbEGv?csFYM=b%3AWzAsWyI2d2tXdSIsNixbInNlbDdFYVlYdEo3WFJTSmxvIl0sImdsVmlMIl1d&csFYM%3Asort=eyJwZWwzdmx5UjBzZUVhNWxyOCI6W3siY29sdW1uSWQiOiJmbGRuQlZBNlhOd3o0andXNyIsImFzY2VuZGluZyI6dHJ1ZX1dfQ)


