---
config:
  theme: neutral
  themeVariables:
    fontSize: 16
---

%% === DATA TYPES ===
classDef vector fill:#B3D1FF, stroke:transparent, stroke-width:2px;  %% Vector data
classDef raster fill:#FFB3B3, stroke:transparent, stroke-width:2px; %% Raster data
classDef lidar fill:#AEE9C1, stroke:transparent, stroke-width:2px;  %% LiDAR data

%% === PROCESS TYPES ===
classDef fieldwork fill:#c1e3e2, stroke:transparent, stroke-width:2px; %% %% Fieldwork / Manual work
classDef python fill:#FFF2A8, stroke:transparent, stroke-width:2px;     %% Python
classDef metashape fill:#FFD1A8, stroke:transparent, stroke-width:2px;  %% Agisoft Metashape
classDef cloudcompare fill:#D6B3FF, stroke:transparent, stroke-width:2px; %% CloudCompare
classDef djiterra fill:#c1cfe3, stroke:transparent, stroke-width:2px; %% DJI Terra


%% === SUBGRAPH STYLES ===
style main stroke:none,fill:transparent;
style legend stroke:none,fill:#f0f0f0;
